config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :recipes, shallow: true do
    collection do
      get "my", to: "recipes#my"
    end
    member do
      get "search"
    end
  end
  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/recipes/ingredients_controller.rb
class Recipes::IngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :fetch_recipe, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index]
    before_action :check_ownership, only: [:edit, :update, :destroy]
    include Ownership
    def index
        @recipes= Recipe.all.order(created_at: :desc)
    end
    def new
        @recipe = Recipe.new
    end
    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.user = current_user
        if @recipe.save
            redirect_to recipe_path(@recipe)
        else
            render :new
        end
    end
    def show
    end
    def edit
    end
    def update
        @recipe.update(recipe_params)
        if @recipe.save
            redirect_to recipe_path(@recipe)
        else
            render :edit
        end
    end
    def destroy
        @recipe.destroy
        flash[:notice] = "Recipe deleted successfully."
        redirect_to recipes_path
    end
    def my
        @recipes=Recipe.where(user: current_user).order(created_at: :desc)
    end

    private
    def recipe_params
        params.expect(recipe:[:title,:instructions])
    end
    def fetch_recipe
        @recipe=Recipe.find(params[:id])
    end
    def check_ownership
        if current_user != @recipe.user
            flash[:alert] = "You are not authorized to edit this recipe."
            redirect_to recipe_path(@recipe) and return
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Recipe Share" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
<nav>
      <%= link_to "Login", new_user_session_path  unless user_signed_in? %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete if user_signed_in? %>
    </nav>
      <%= yield %>
    </body>
  </html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
    <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    </div>
    <div>
    <%= form.label :instructions %>
    <%= form.text_area :instructions %>
    </div>
    <%= form.submit %>
<% end %>

app/views/recipes/edit.html.erb
<%= render "form", recipe: @recipe %>
<% link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1> Recipes </h1>
<% if @recipes.any? %>
    <ul>
        <% @recipes.each do |recipe| %>
            <li>
                <%= link_to recipe.title, recipe %>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>No recipes found.</p>
<% end %>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/my.html.erb
<h1> Recipes </h1>
<% if @recipes.any? %>
    <ul>
        <% @recipes.each do |recipe| %>
            <li>
                <%= link_to recipe.title, recipe %>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>No recipes found.</p>
<% end %>

<%= link_to 'New Recipe', new_recipe_path %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/new.html.erb
<%= render "form", recipe: @recipe%>
<%= link_to 'Back', root_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<p> <%= @recipe.instructions %></p>
<%= link_to 'Edit', edit_recipe_path(@recipe) if current_user == @recipe.user %>
<%= link_to 'Back', recipes_path %>